name: phone_tech_london
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependency_overrides:
  platform: ^3.1.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  synchronized: 3.0.0
  http: any                        #used for api call
  shared_preferences: ^2.0.5          #used for store data locally on team bases
  intl:
  url_launcher: ^6.0.10
  get: ^4.6.1
  dartz: ^0.10.0
  retrofit: ^3.0.0
  json_annotation: 4.4.0
  json_serializable: 6.1.3
  retrofit_generator: any
  build_runner: any
  logger: any
  pretty_dio_logger: ^1.1.1
  image_crop: ^0.4.0
  image_picker: ^0.8.5+3





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

